---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaskapp
  name: deploy-flaskapp
  namespace: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp
  strategy: {}
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      imagePullSecrets:
      - name: dockersecret
      containers:
        # - image: srir27/flaskapp:v2
        - image: srir27/sriprvt # Private docker repo
          name: flaskapp
          resources: {}
          envFrom: 
          - configMapRef:
              name: flaskapp-cm
            
status: {}
