---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaskapp
  name: deploy-flaskapp
  namespace: flaskapp

spec:
  replicas: 2

  selector:
    matchLabels:
      app: flaskapp

  template:
    metadata:
      labels:
        app: flaskapp

    spec:
      imagePullSecrets:
        - name: dockersecret

      containers:
        - image: srir27/flaskapp:v2
          name: flaskapp

          resources:
            limits:
              cpu: 20m
            requests:
              cpu: 10m

          envFrom:
            - configMapRef:
                name: flaskapp-cm

          volumeMounts:
            - name: flask-storage
              mountPath: /mnt/data

      volumes:
        - name: flask-storage
          persistentVolumeClaim:
            claimName: flaskapp-pvc