apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flaskapp-pvc
  namespace: flaskapp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: manual