apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92Mi8iOnsidXNlcm5hbWUiOiJzcmlyMjciLCJwYXNzd29yZCI6ImRja3JfcGF0X2poMG9SYWpRbWlzb1FLbGNLVnN6VE9HSzVvTSIsImVtYWlsIjoic3JpYmFsYWppNzcwOEBnbWFpbC5jb20iLCJhdXRoIjoiYzNKcGNqSTNPbVJqYTNKZmNHRjBYMnBvTUc5U1lXcFJiV2x6YjFGTGJHTkxWbk42VkU5SFN6VnZUUT09In19fQ==
kind: Secret
metadata:
  name: dockersecret
  namespace: flaskapp
type: kubernetes.io/dockerconfigjson
