# stage 1
FROM python:3.12-slim as build

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

COPY . /app/

# stage 2
FROM python:3.12-slim

WORKDIR /app

COPY --from=build /install /usr/local
COPY --from=build /app /app

RUN useradd --create-home appuser

USER appuser

EXPOSE 8000

ENTRYPOINT [ "gunicorn" ]

CMD [ "webappdckr.wsgi:application", "--bind", "0.0.0.0:8000" ]


