# stage 1
FROM python:3.12-slim as build
# set workdir
WORKDIR /app
# copy requirements to workdir
COPY requirements.txt /app/
# install the requirements into /install (a staging dir), preserving the /usr/local directory structure
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt
# copy the project folder to the workdir
COPY . /app/

# stage 2
FROM python:3.12-slim
# set workdir
WORKDIR /app
# copy the installed packages and softwares into /usr/local from the previous stage
COPY --from=build /install /usr/local
# copy the application code from the previous stage to the current workdir
COPY --from=build /app /app
# create a new user (not root)
RUN useradd --create-home appuser

# use the newly created user
USER appuser

# this image's application is expected to listen on port 8000 inside the container
EXPOSE 8000

# use gunicorn to start the django application
ENTRYPOINT [ "gunicorn" ]

# the default commands while running
CMD [ "webappdckr.wsgi:application", "--bind", "0.0.0.0:8000" ]

